version: '3'

volumes:
    pgdata:
        driver: local
services:
#-----------------postgres-----------------------
    postgres:
        image: postgres:9.3.22
        restart: always
        ports:
            - 5432:5432
        volumes:
            - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql
#-----------------django-----------------------
    django:
        restart: always
        build:
            context: .
            dockerfile: /home/docker/django/Dockerfile
        volumes:
            - ./cleverbots:/home/cleverbots
            - ./cleverbots/static:/home/cleverbots/static
            - ./cleverbots/media:/home/cleverbots/media
        ports:
            - 8000:8000
        depends_on:
            - postgres
        command: gunicorn -c gunicorn.py cleverbots.wsgi
#-----------------nginx-----------------------
    nginx:
        restart: always
        image: nginx:latest
        ports:
          - 80:80
        volumes:
            - ./cleverbots/static:/home/cleverbots/static
            - ./cleverbots/media:/home/cleverbots/media
            - ./cleverbots/logs:/home/cleverbots/logs
            - ./docker/nginx:/home/cleverbots/docker/nginx/cleverbots.conf
            - ./docker/nginx:/etc/nginx/conf.d
        depends_on:
            - django
        command: nginx -g 'daemon off;'


