version: '3'

# хранилища
volumes:
    pgdata:
        driver: local
services:
#-----------------nginx-----------------------
    nginx:
# при падении будет стараться подняться
        restart: always
# только свежий nginx
        image: nginx:latest
# слушает порт 80
        expose:
          - 80
        ports:
          - "80:80"
# монтируем только те директории, в которых лежит статика, т.к. nginx с динамикой не будет работать. Также директорию с логами и файл настройки, который мы подготовили.
        volumes:
            - ./cleverbots/static:/home/cleverbots/static;
            - ./cleverbots/media:/home/cleverbots/media;
            - ./docker/nginx:/home/cleverbots/docker/nginx/cleverbots.conf
# и nginx зависит от контейнера python. Т.е. python должен быть запущен первым
        depends_on:
            - django
#-----------------django-----------------------
    django:
        restart: always
# указываем откуда собирать образ
        build:
            context: .
            dockerfile: /home/docker/python/Dockerfile
# монтируем директорию проекта
        volumes:
            - ./cleverbots:/home/cleverbots
        expose:
          - 8000
        ports:
            - 8000:8000
# запускаем gunicorn
        command: "gunicorn -c gunicorn.py cleverbots.wsgi"
#-----------------postgres---------------------

