# Generated by Django 2.1.4 on 2019-04-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190407_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={},
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='created',
        ),
        migrations.AddField(
            model_name='snippet',
            name='image',
            field=models.ImageField(blank=True, upload_to='uploaded_images'),
        ),
    ]
