# Generated by Django 2.1.4 on 2019-04-15 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190415_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='title',
            new_name='place',
        ),
        migrations.AddField(
            model_name='snippet',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='snippet',
            name='image',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
