# Generated by Django 2.1.3 on 2019-04-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_remove_snippet_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
