# Generated by Django 2.1.4 on 2019-04-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20190415_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='date',
        ),
    ]
