# Generated by Django 2.1.4 on 2019-04-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='size',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
