# Generated by Django 2.1.4 on 2019-04-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_snippet_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
