# Generated by Django 2.1.4 on 2019-04-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_snippet_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
